# Generated by Django 4.1 on 2022-08-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('AccountID', models.AutoField(primary_key=True, serialize=False)),
                ('AccountName', models.CharField(max_length=100)),
                ('AccessDescription', models.CharField(max_length=100)),
                ('DateOfJoining', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Levelaccess',
            fields=[
                ('AccessLevelID', models.AutoField(primary_key=True, serialize=False)),
                ('AccessDescription', models.CharField(max_length=100)),
            ],
        ),
    ]
