# Generated by Django 4.1 on 2022-08-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('AccountID', models.AutoField(primary_key=True, serialize=False)),
                ('AccountName', models.CharField(max_length=100)),
                ('AccessDescription', models.CharField(max_length=100)),
                ('DateOfJoining', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
